# azure-pipelines.yml

variables:
  CLOUD_MANAGER_CREDENTIALS: $(CLOUD_MANAGER_CREDENTIALS)

trigger:
  branches:
    include:
      - main  # Replace with your desired branch or use '*' to include all branches

pr: none  # Disabling Pull Request triggers for simplicity. You can enable it if needed.

pool:
  vmImage: 'ubuntu-latest'  # Use an appropriate image for your script (Windows, macOS, etc.)

steps:
- checkout: self  # This will checkout the default branch of the current repository
  persistCredentials: true
  clean: true  # Clean any left-over artifacts from previous runs

- script: |
    TARGET_GIT="https://$(CLOUD_MANAGER_CREDENTIALS)@github.com/mayurb-org/aem-devops.git"
    # Set up the adobe repository as a remote
    git remote add adobe ${TARGET_GIT}

    # Fetch and pull changes from the source repository
    git fetch origin
    git pull origin main

    # Push changes to the target repository
    git push adobe main

  displayName: 'Sync Source to Target Repository'

