# azure-pipelines.yml
variables:
  CM_CREDENTIALS: $(CLOUD_MANAGER_CREDENTIALS)
  GIT_USER: $(gitusername)

trigger:
  branches:
    include:
      - "*"

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
    persistCredentials: true
    clean: true
    fetchDepth: 0

  - script: |
      # Authenticate with GitHub using the personal access token
      git config --global user.email "azure-pipelines@noreply.com"
      git config --global user.name "Azure Pipelines"
      git config --global credential.helper "store --file=.git/credentials"
      echo -e "protocol=https\nhost=github.com\nusername=$(gitusername)\npassword=$(CM_CREDENTIALS)\n" > .git/credentials
      cat .git/credentials
    displayName: 'Authenticate with GitHub'

  - script: |      
      git config --global --unset credential.helper
      TARGET_GIT="https://github.com/mayurb-org/aem-devops.git"
      echo "GIT_REF=${TARGET_GIT}"
      git remote add adobe ${TARGET_GIT}
      cat .git/config
    displayName: 'Add remote repo'

  - script: |
      if [ "$(Build.Reason)" == "PullRequest" ]; then
        BRANCH_NAME=$(echo $BUILD_SOURCE_BRANCH | sed 's/refs\/heads\///')
      elif [ "$(Build.Reason)" == "IndividualCI" ]; then
        BRANCH_NAME=$(echo $BUILD_SOURCEBRANCH | sed 's/refs\/heads\///')
      fi
      echo "BRANCH_NAME=${BRANCH_NAME}"

      git fsck --full
      git fetch origin
      ls -ltrha
      git push -f -v adobe HEAD:${BRANCH_NAME} --force
    displayName: 'Get branch name and Sync (push)'
    condition: and(succeeded(), eq(variables['Build.Reason'], 'IndividualCI'))

  - script: |
      if [ "$(Build.Reason)" == "PullRequest" ]; then
        if [ $(PR.SourceBranch) != "refs/heads/main" ]; then
          BRANCH_NAME=$(echo $(PR.SourceBranch) | sed 's/refs\/heads\///')
          git push --delete -f -v adobe ${BRANCH_NAME} 
        fi
      fi
    displayName: 'Remove branch (delete)'
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
