# azure-pipelines.yml
variables:
  CLOUD_MANAGER_CREDENTIALS: $(CLOUD_MANAGER_CREDENTIALS)

trigger:
  branches:
    include:
      - main

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  - script: |
      TARGET_GIT="https://$(CLOUD_MANAGER_CREDENTIALS)@github.com/mayurb-org/aem-devops.git"
      echo "GIT_REF=${TARGET_GIT}"
      git remote add adobe ${TARGET_GIT}
      cat .git/config
    displayName: 'Add remote'

  - script: |
      if [ "$(Build.Reason)" == "PullRequest" ]; then
        BRANCH_NAME=$(echo $BUILD_SOURCE_BRANCH | sed 's/refs\/heads\///')
      elif [ "$(Build.Reason)" == "IndividualCI" ]; then
        BRANCH_NAME=$(echo $BUILD_SOURCEBRANCH | sed 's/refs\/heads\///')
      fi
      echo "BRANCH_NAME=${BRANCH_NAME}"
    displayName: 'Get branch name'

  - script: |
      echo $(BRANCH_NAME)
      ls -ltrh
      git checkout $(BRANCH_NAME)
      git push -f -v adobe $(BRANCH_NAME)
    displayName: 'Sync branch (push)'
    condition: and(succeeded(), eq(variables['Build.Reason'], 'IndividualCI'))

  - script: |
      if [ "$(Build.Reason)" == "PullRequest" ]; then
        if [ $(PR.SourceBranch) != "refs/heads/main" ]; then
          BRANCH_NAME=$(echo $(PR.SourceBranch) | sed 's/refs\/heads\///')
          git push --delete -f -v adobe $(BRANCH_NAME)
        fi
      fi
    displayName: 'Remove branch (delete)'
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
