# azure-pipelines.yml

variables:
  CLOUD_MANAGER_CREDENTIALS: $(CLOUD_MANAGER_CREDENTIALS)

trigger:
  branches:
    include:
      - main

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      TARGET_GIT="https://$(CLOUD_MANAGER_CREDENTIALS)@github.com/mayurb-org/aem-devops.git"
      echo "GIT_REF=${TARGET_GIT}"
      git remote add adobe ${TARGET_GIT}
      cat .git/config
    displayName: 'Add remote'

  - script: |
      echo $(Build.Reason)
      echo "==============================="
      echo "==============================="
      echo $(Build.SourceBranchName)
      echo "==============================="
      echo "==============================="
      echo $(Build.SourceBranch)
      echo "==============================="
      echo "==============================="
      if [ "$(Build.Reason)" == "PullRequest" ]; then
        BRANCH_NAME=$(Build.SourceBranchName)	
      elif [ "$(Build.Reason)" == "IndividualCI" ]; then
        BRANCH_NAME=$(Build.SourceBranchName)
      elif [ "$(Build.Reason)" == "Manual" ]; then
        BRANCH_NAME=$(Build.SourceBranchName)
      fi
      echo "BRANCH_NAME=${BRANCH_NAME}"
    displayName: 'Get branch name'

  - script: |
      git checkout ${BRANCH_NAME}
      git push -f -v adobe ${BRANCH_NAME}
    displayName: 'Sync branch (push)'
    condition: and(succeeded(), eq(variables['Build.Reason'], 'IndividualCI'))

  - script: |
      if [ "$(Build.Reason)" == "PullRequest" ]; then
        if [ $(System.PullRequest.SourceBranch) != "refs/heads/master" ]; then
          BRANCH_NAME=$(echo $(System.PullRequest.SourceBranch) | sed 's/refs\/heads\///')
          git push --delete -f -v adobe $(BRANCH_NAME)
        fi
      fi
    displayName: 'Remove branch (delete)'
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))